---
title: "R Notebook"
output: html_notebook
---
```{r}

df <- fp_stats("QB", season = 2016, start_week = 1, end_week = 1)


```

```{r}

library(stringr)

x <- 4
str_glue('{x}')

```


```{r}
# This code is used to extract the weekly data for each nfl season
# The other data is downloaded manually

library(fantasypros)
library(stringr)

years = list('2016', '2017', '2018', '2019', '2020', '2021', '2022')

positions <- list("QB", "RB", "WR", "TE", "K", "DST")
weeks <- 1:17

```


```{r}

# get all stats
get_data <- function(years) {
  for (year in years) {
    for (pos in positions) {
      if (year >= 2021) {
        weeks <- 1:18
      }
      for (week in weeks) {
        df <-
          fp_stats(
            pos,
            season = year,
            start_week = week,
            end_week = week,
            scoring = "ppr"
          )
        if (file.exists("data/all_stats/all_stats.csv")) {
          names = FALSE
        }
        else {
          names = TRUE
        }
        write.table(
          df,
          str_glue("data/all_stats/all_stats.csv"),
          append = TRUE,
          sep = ',',
          quote = FALSE,
          col.names = names,
          row.names = FALSE
        )
      }
    }
  }
}
```


```{r}

get_data(years)

```

```{r}

# get snap counts data
get_snap_data <- function(years) {
  for (year in years) {
    df <- fp_snap_counts(season = year)
    if (file.exists("data/snap_data/snap_counts.csv")) {
      names = FALSE
    }
    else {
      names = TRUE
    }
    write.table(
      df,
      str_glue("data/snap_data/snap_counts.csv"),
      append = TRUE,
      sep = ',',
      quote = FALSE,
      col.names = names,
      row.names = FALSE
    )
  }
}

```


```{r}

get_snap_data(years)

```



```{r}

# get target counts data
get_target_data <- function(years) {
  for (year in years) {
    df <- fp_targets(season = year)
    if (file.exists("data/target_data/target_counts.csv")) {
      names = FALSE
    }
    else {
      names = TRUE
    }
    write.table(
      df,
      str_glue("data/target_data/target_counts.csv"),
      append = TRUE,
      sep = ',',
      quote = FALSE,
      col.names = names,
      row.names = FALSE
    )
  }
}

```


```{r}

get_target_data(years)

```




```{r}

# get team target counts data
get_team_target_data <- function(years) {
  for (year in years) {
    if (year >= 2021) {
        weeks <- 1:18
    }
      for (week in weeks) {
        df <-
          fp_team_targets(
            season = year,
            start_week = week,
            end_week = week
          )
        if (file.exists("data/team_target_data/team_target_counts.csv")) {
          names = FALSE
        }
        else {
          names = TRUE
        }
        write.table(
          df,
          str_glue("data/team_target_data/team_target_counts.csv"),
          append = TRUE,
          sep = ',',
          quote = FALSE,
          col.names = names,
          row.names = FALSE
        )
    }
  }
}

```


```{r}

get_team_target_data(years)

```



